### ISSUE TITLE
Adjust chart widths on resize

### ISSUE THREAD

**Issue by AndrewRook** [AndrewRook/NFLDash#13]
Right now they're hardcoded, which is super duper ugly. Looks like there should be some support for that based on [this issue](https://github.com/dc-js/dc.js/issues/544) and [this example gallery](http://dc-js.github.io/dc.js/resizing/).

**Comment by caravinden** [comment]
AndrewRook that is Awesome. I have another query regarding with chart resize. Above solution will work for single chart view, If there are many charts are displayed on the screen and try to make resize how the width and height will be calculated.

**Comment by AndrewRook** [comment]
Each chart is in its own div, so when you resize the window every chart resizes inside its own div by grabbing that div's width. Or at least, that's how I understand that it works, some of this is was just trial and error.
